### ISSUE TITLE
Possible versioning issue with clean install

### ISSUE THREAD

**Issue by tojon** [taskcluster/unified-logviewer#33]
I tried a clean install in a new locally cloned repo, and the out of the box install experience appears to have  issues, and the subsequent `npm start` fails. I think there may be a Neutrino version that needs updating or modification, but I defer to you guys. It could be pilot error on my part, but I simply followed the ReadMe.

I've attached my console output from the `npm install`, and my subsequent `npm start` log.

OS: OSX 10.11.5

```
npm WARN deprecated neutrino-preset-base@2.0.1: neutrino-preset-base is no longer used with Neutrino v4+
```

[unified-logviewer-npm-debug-log.txt](https://github.com/taskcluster/unified-logviewer/files/887774/unified-logviewer-npm-debug-log.txt)

[unified-logviewer-npm-install-console.txt](https://github.com/taskcluster/unified-logviewer/files/887773/unified-logviewer-npm-install-console.txt)

**Comment by eliperelman** [comment]
Yeah, this is just a deprecation message for the upcoming Neutrino version, and it should still function properly. Unless npm/yarn actually blows up with an error while installing, you are usually OK to continue.

That said, I'll be upgrading this repo to use Neutrino v5 very soon, and then this message will go away.

**Comment by tojon** [comment]
Ok.

For what its worth if you look at the second txt file I attached above (unified-logviewer-npm-install-console.txt), it appears to show those related problems with the install. Basically the current repo doesn't appear to correctly install, or run at present.

**Comment by eliperelman** [comment]
@tojon ah, I see. That's because your Node.js version is listed as 0.12.0. The logviewer requires Node.js v6.9+ (because Neutrino requires Node.js 6.9+).

**Comment by tojon** [comment]
@eliperelman Ah, mystery solved. Thank you! This Issue is a non-issue; outside the discussed Neutrino update.
