### ISSUE TITLE
Remove upper margin in log container

### ISSUE THREAD

**Issue by tojon** [taskcluster/unified-logviewer#34]
I think it might be helpful to remove the margin at the top of the TaskCluster and Treeherder instances of the Logviewer, since it doesn't appear to serve a purpose, other than consuming space. I understand TaskCluster has its 'settings gear' at the right hand side, but that operates happily over log line content during scrolling anyway.

If there are other apps using unified-logviewer other than TaskCluster and Treeherder, or scenarios where that margin is needed, let me know.

I will put up a PR so you can evaluate the difference, and merge or not if you wish.

**Comment by eliperelman** [comment]
Yeah, this would be welcome.

**Comment by eliperelman** [comment]
Resolved via #35.
